services:
  # 1. CONTENEDOR DEL BACKEND (LARAVEL)
  backend:
    build: 
      context: ./laravel-backend
    container_name: uranusdata-backend
    volumes:
      - ./laravel-backend:/app
      - backend_vendor:/app/vendor
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=uranusdata
      - DB_USERNAME=uranusdata_user
      - DB_PASSWORD=uranusdata_password
      - PHP_CLI_SERVER_WORKERS=4
    depends_on:
      - mysql
    networks:
      - uranusdata

  # 2. CONTENEDOR DEL FRONTEND (ANGULAR)
  frontend:
    build: 
      context: .
    container_name: uranusdata-frontend
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/laravel-backend
    ports:
      - "4200:4200"
    networks:
      - uranusdata

  # 3. CONTENEDOR DE BASE DE DATOS (MYSQL)
  mysql:
    image: mysql:8.0
    container_name: uranusdata-mysql
    command: --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uranusdata
      MYSQL_USER: uranusdata_user
      MYSQL_PASSWORD: uranusdata_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - uranusdata

volumes:
  mysql_data:
  backend_vendor:

networks:
  uranusdata:
    driver: bridge